version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  user-service:
    build:
      context: ./backend/user-service
    ports:
      - "3002:3002"
    env_file:
      - ./backend/user-service/.env

  question-service:
    build:
      context: ./backend/question-service
    ports:
      - "3001:3001"
    env_file:
      - ./backend/question-service/.env

  matching-service:
    build:
      context: ./backend/matching-service
    ports:
      - "3003:3003"
    env_file:
      - ./backend/matching-service/.env
    environment:
      - REDIS_HOST=redis  
    depends_on:
      - redis

  collaboration-service:
    build:  
      context: ./backend/collaboration-service
    ports:
      - "3006:3006"
    env_file:
      - ./backend/collaboration-service/.env